name: github actions CI
on: push
jobs:
  Clone
    name: clone repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .